### ISSUE TITLE
How to stub or config :no_direct_assignment to false when make rspec on rails?

### ISSUE THREAD

**Issue by vfa-danhnt** [aasm/aasm#223]
Hi all,

I am newbie AASM. I just tried to use AASM on my project.
I have a problem: at Model
<pre>
<code class=ruby>
class Job
  include AASM

  aasm :no_direct_assignment => true do
    state :sleeping, :initial => true
    state :running
    state :cleaning
    event :run do
      transitions :from => :sleeping, :to => :running
    end
    event :clean do
      transitions :from => :running, :to => :cleaning
    end
    event :sleep do
      transitions :from => [:running, :cleaning], :to => :sleeping
    end
  end
end
</code>
</pre>

And on rspec unit test

<pre>
<code class=ruby>
...
describe '#clean!' do
    before do
      AASM::Configuration.stub(:no_direct_assignment).and_return(false)
    end
    describe 'Job clearning cancel' do
      let(:job) { FactoryGirl.create(:job, aasm_status: 'running') }
      context "when status is 'running'" do
        it "should update to cleaning" do
          job.clean!
          job.reload
          job.aasm_status.should eql 'cleaning'
        end
      end
    end
  end
...
</code>
</pre>
When i run rspec i got error: 
<code>
Failure/Error: let(:job) { FactoryGirl.create(:job, aasm_status: 'running') }
     AASM::NoDirectAssignmentError:
       direct assignment of AASM column has been disabled (see AASM configuration for this class)
</code>

Please share me any idea to make pass unit test.
How can i stub :no_direct_assignment right?

**Comment by sivagollapalli** [comment]
@vfa-danhnt Have you tried `allow(AASM::Configuration).to receive(:no_direct_assignment).and_return(false)` this way?

**Comment by alto** [comment]
Hi @vfa-danhnt 

You can always change the configuration like this:

```ruby
  before do
    Job.aasm.state_machine.config.no_direct_assignment = false
  end
```

Does that work for you?

**Comment by toobulkeh** [comment]
neither of these worked for me.
This is important to use for migrations where we temporarily want to allow direct assignment when changing data on the backend.

**Comment by alto** [comment]
@toobulkeh  I will take a closer look then today.

**Comment by alto** [comment]
@toobulkeh Yes, you are right. My suggestion didn't work.

I fixed this now, allowing to use

```ruby
  before do
    Job.aasm.state_machine.config.no_direct_assignment = false
  end
```

The change will be released with the upcoming minor update `4.2.0`. Feel free to use it now (using the *master* branch).

**Comment by toobulkeh** [comment]
Thanks!

**Comment by alto** [comment]
I just released version `4.2.0` including the patch.

**Comment by mtsbarbosa** [comment]
@alto i'm sorry digging it back, but I am trying to use FactoryGirl and defining aasm_state inside of the definition. This is giving me some similar problem:

    unrecognized state-type given

if I change the no_direct_assignment configuration this problem should be resolved? Where can I find this configuration?

**Comment by RoniLeshes** [comment]
@alto your solution doesn't work for me in 5.2.0. I am using MiniTest and I still get the error. Example: 
```ruby
setup do
    Order.aasm.state_machine.config.no_direct_assignment = false
    @stub_order = Order.new(id: 123, status: :cancelled) # <-- This fails with Minitest::UnexpectedError: AASM::NoDirectAssignmentError: direct assignment of AASM column has been disabled (see AASM configuration for this class)
end
```

Initializing a data model without saving or running AASM validations should be easy yet I have wasted like 2 hours just trying to overcome this
