### ISSUE TITLE
Success Callback triggers before fully committed

### ISSUE THREAD

**Issue by softwaregravy** [aasm/aasm#683]
Let me start off -- this was unexpected behavior for me. Maybe this is by design. Maybe I'm missing something and there's a way to do this properly. 

**Describe the bug**
The success callback seems to be getting triggered prior to the data actually being committed in the db

Rails 5.2.4.1
aasm 5.0.8
pg 1.2.2

**To Reproduce**

1) have a success block defined on a transition which calls a function passing your own id as an argument. (This is a very common idiom for sidekiq jobs.) The receiving function will attempt to load the object from the db by id. The loaded object will have the old state. So, in the success block, the state has not yet been persisted. 

(I am tracing, but I suspect the transaction has not yet been closed.)

**Expected behavior**
The success block should be called after everything is done successfully -- the new state should be available in the db. 

Since this is not yet committed, I suspect this could still fail to save the transition. So, IMHO, this should really be triggered outside of the transaction.

***Bad Pseudo Code***

```ruby
class Flow < ApplicationRecord
  include AASM

  asm do 
    state :ready, initial: true
    state :running
    state :completed

    event :start do
      transitions from: :ready, to: :running, 
        success: -> { RunFlowJob.perform_async(self.id) }
    end

    event :done do
      transitions from: :running, to: :completed
    end
  end
end

class RunFlowJob
  include Sidekiq::Worker

  def perform(flow_id)
    flow = Flow.find(flow_id)
    raise "wrong state!" unless flow.aasm_state == "running" # <-this sometimes throws an exception
    # do work here
    flow.done!
  end
end

# somewhere else in my program
flow = Flow.create
flow.start!
```

***Demo in my logs ***

I put the following in my success block of a transition to demonstrate:
```ruby
puts "in the success block!"
```

and I get

```
2.6.5 :030 > flow.next_step!
   (0.3ms)  BEGIN
  BulkImportFlow Update (0.6ms)  UPDATE "bulk_import_flows" SET "updated_at" = $1, "aasm_state" = $2 WHERE "bulk_import_flows"."id" = $3  [["updated_at", "2020-05-25 02:20:38.725161"], ["aasm_state", "preparing"], ["id", 68]]
in the success block!
   (0.6ms)  COMMIT
 => true
```

**Comment by softwaregravy** [comment]
Looks like this was introduced [here](https://github.com/aasm/aasm/pull/239/files)

Firing of the `success` callback is called from [here](https://github.com/aasm/aasm/blob/d65df64db6ddd89dec4b186c78a6da501c0d8979/lib/aasm/aasm.rb#L161)

That method, `aasm_fired` is called from [here](https://github.com/aasm/aasm/blob/d65df64db6ddd89dec4b186c78a6da501c0d8979/lib/aasm/aasm.rb#L107) which looks like it's called from the [AASM#Persistence#ORM class] via (https://github.com/aasm/aasm/blob/1cf15ed16e45cb54cf2b3f7fcd065c7f938cb277/lib/aasm/persistence/orm.rb#L132) `super` 

Please let me know if I've got that right.

Assuming that's the right trace, we're inside the transaction form the ORM

Assuming we want the `success` callback on the transition to be after the state has been successfully committed, I would suggest moving the callback down to the `if success` block [in the ORM class](https://github.com/aasm/aasm/blob/1cf15ed16e45cb54cf2b3f7fcd065c7f938cb277/lib/aasm/persistence/orm.rb#L138), where the `aasm_execute_after_commit` call happens

This would mean something like:

```ruby
# in aasm/orb starting at line 128
# https://github.com/aasm/aasm/blob/1cf15ed16e45cb54cf2b3f7fcd065c7f938cb277/lib/aasm/persistence/orm.rb#L138
if success
  aasm_execute_after_commit do
    event.fire_transition_callbacks(:success, self, *args)
    event.fire_callbacks(:after_commit, self, *args)
    event.fire_global_callbacks(:after_all_commits, self, *args)
  end
end
```

What are your thoughts on this approach?

**Comment by anilmaurya** [comment]
Hi @softwaregravy 

Thank you for reporting and your investigation.
`success` callback for transition is executed when `persist_successful` is true which is defined [here](https://github.com/aasm/aasm/blob/d65df64db6ddd89dec4b186c78a6da501c0d8979/lib/aasm/aasm.rb#L157) 

So order of execution is correct, first state update query is sent to database and then `success` callback is initiated.

In some case (like yours) when database is facing huge load, it's possible that update query will take some time to execute and in meantime `success` callback will be executed.
For such scenario where callback should be triggered after database is updated, AASM recommend using `after_commit` callback which is defined on event.

Let me know if this does not solve your problem.

**Comment by softwaregravy** [comment]
I'm referring to the `success` callback on the transition. Is there an `after_commit` on the transition? I didn't see one. Or are you suggesting I change my implementation to use event callbacks instead of transition callbacks?

If this is by design, then maybe we can update the [docs](https://github.com/aasm/aasm#lifecycle) which indicate that the state is updated before the transition#success callback is called.



(Not that it matters, but this is normal execution with zero load. I just have a worker sitting idle waiting for the job as soon as it gets submitted another process, so as soon as they get the id they query right away. There's no delay on the commit due to any load on system or db.)

**Comment by softwaregravy** [comment]
The link you provided is the same I provided. Is that not called from inside the transaction from the ORM class I linked?

**Comment by anilmaurya** [comment]
@softwaregravy Yes, `aasm_fire_event` is called from ORM class. I gave you link for `set_current_state_with_persistence`, It is fired before `success` callback on transition. In this method DB update query is fired. So, state is updated before the transition#success callback is called.

Can you give me a failing test to prove that success callback is triggered before state update query is fired.

I am suggesting you to use event's callback `after_commit`

**Comment by softwaregravy** [comment]
My example above shows the puts in the success block followed by the commit. 

where `set_current_state_with_persistence` is being called is still inside [the db transaction](https://github.com/aasm/aasm/blob/1cf15ed16e45cb54cf2b3f7fcd065c7f938cb277/lib/aasm/persistence/orm.rb#L131). So there is no state saved to the db yet. No persist has happened.

From what I can tell: 
The callbacks from the [ORM](https://github.com/aasm/aasm/blob/1cf15ed16e45cb54cf2b3f7fcd065c7f938cb277/lib/aasm/persistence/orm.rb#L138) are called after persisting, but the callbacks from [aasm](https://github.com/aasm/aasm/blob/d65df64db6ddd89dec4b186c78a6da501c0d8979/lib/aasm/aasm.rb#L158) which you linked, are being called from inside the transaction, and the persist is not yet complete. 

I whipped up a quick [demo](https://github.com/softwaregravy/aasm-success-demo). It shows that the values are not yet persisted to the DB when the `success` callback is triggered.

**Comment by softwaregravy** [comment]
Also, the `job_gone_wrong` event I added to the demo will cause deadlock.

**Comment by anilmaurya** [comment]
Hi @softwaregravy 

Thank you for providing quick demo to explain this issue.

I think it make sense to move success callback in `aasm_execute_after_commit`
Are you interested in sending a PR for fix ?

**Comment by softwaregravy** [comment]
Yes. I'll find some time this week.

**Comment by anilmaurya** [comment]
Hi @softwaregravy 

I tried solution mentioned by you but it has consequences which I didn't thought before.
It will change the order of callback execution which is a breaking change.

Therefore I updated README to clarify that database update is not guaranteed in `success` callback and to use `after_commit` callback if you need to execute callback after database update.

I verified that using `after_commit` will solve problem which you are facing in [demo](https://github.com/softwaregravy/aasm-success-demo)

**Comment by softwaregravy** [comment]
fair enough

**Comment by theonegri** [comment]
@anilmaurya IMO this i still an issue.
`after_commit` is known to create race conditions in some cases:
> Please note that :after_commit AASM callbacks behaves around custom implementation of transaction pattern rather than a real-life DB transaction. This fact still causes the race conditions and redundant callback calls within nested transaction. 

I can't seem to find any callback at the transition or event level which is guaranteed to be fired after the state is changed in the database/after the database commit.

**Comment by theonegri** [comment]
One solution could be to introduce another callback called `after_succes`?

**Comment by anilmaurya** [comment]
Hi @theonegri 
```
In order to fix that it's highly recommended to add gem 'after_commit_everywhere', '~> 1.0' to your Gemfile.
```

**Comment by theonegri** [comment]
@anilmaurya Yes but `after_commit_everywhere` has consequences across the whole source code of the rails app and that's not ideal. 

I would rather not impact the entire app with `after_commit_everywhere`. IMO a native way to guarantee a callback will be fired after the state is changed in the database/after the database commit would be preferable.

**Comment by ckornaros** [comment]
@anilmaurya Is 'after_commit_everywhere' gem recommended when we use ActiveRecord or only if we use AR and after_commit callback on the event ? Should we just add the gem or also add 'include AfterCommitEverywhere' in some classes ?

@theonegri Did you find an alternative to avoid using 'after_commit_everywhere' ?

Is there an implementation like after_commit but for the transition instead of the event ?

**Comment by pzac** [comment]
I had the same issue and ended up adding an ugly loop to wait until the new state is committed - I don't want to add `after_commit_everywhere`. Better solutions are welcome!

**Comment by theonegri** [comment]
ping @anilmaurya
