### ISSUE TITLE
after callback not working in transition scope

### ISSUE THREAD

**Issue by jkojro** [aasm/aasm#737]
```
event :run, after: :notify_somebody do
     transitions from: :sleeping, to: :running, after:  :notifi_somebody_else
```

Actual behaviour:
Record in `notify_somebody` method is in `running` state, but `notifi_somebody_else` is triggered when record is still in `sleeping` state.

Expected behaviour:
`after` callback is triggered after record changes state (is in running state)`

**Comment by oscarada87** [comment]
same problem using aasm 5.0.5

**Comment by MarkZsombor** [comment]
I had the same issue today with 5.2.0, the callback fired before the state was updated in the DB.

**Comment by ChandanChainani** [comment]
Issue seems to have been resolved tested with below example with aasm version `5.2.0`
```
class Job
  include AASM
  aasm do
    state :sleeping, :initial => true
    state :running

    event :run, after: :notify_somebody do
      transitions from: :sleeping, to: :running, after:  :notifi_somebody_else
    end
  end

  def notify_somebody()
    puts "notified"
  end

  def notifi_somebody_else()
    puts "called"
  end
end

j = Job.new
j.run
puts j.aasm.current_state # :running
```
@anilmaurya please close the issue.

**Comment by oscarada87** [comment]
@ChandanChainani , first of all, thanks for the response.
I've tested in aasm version `5.2.0`, but the problem was not resolved.

Expected behaviour:
state is already `:running` when `:notifi_somebody_else` was called

Here is my testing code, slightly changed from yours

```
class Job
  include AASM
  aasm do
    state :sleeping, :initial => true
    state :running

    event :run, after: :notify_somebody do
      transitions from: :sleeping, to: :running, after:  :notifi_somebody_else
    end
  end

  def notify_somebody()
    puts "notify_somebody"
  end

  def notifi_somebody_else()
    puts "job state: #{aasm.current_state}"
    puts "notifi_somebody_else"
  end
end

j = Job.new
j.run
# job state: sleeping
# notifi_somebody_else
# notify_somebody
```

**Comment by ChandanChainani** [comment]
> @ChandanChainani , first of all, thanks for the response. I've tested in aasm version `5.2.0`, but the problem was not resolved.
> 
> Expected behaviour: state is already `:running` when `:notifi_somebody_else` was called
> 
> Here is my testing code, slightly changed from yours
> 
> ```
> class Job
>   include AASM
>   aasm do
>     state :sleeping, :initial => true
>     state :running
> 
>     event :run, after: :notify_somebody do
>       transitions from: :sleeping, to: :running, after:  :notifi_somebody_else
>     end
>   end
> 
>   def notify_somebody()
>     puts "notify_somebody"
>   end
> 
>   def notifi_somebody_else()
>     puts "job state: #{aasm.current_state}"
>     puts "notifi_somebody_else"
>   end
> end
> 
> j = Job.new
> j.run
> # job state: sleeping
> # notifi_somebody_else
> # notify_somebody
> ```

@oscarada87 `after` callback will be called after the state has been updated so it is correct the state is `:running` inside `notifi_somebody_else` callback

**Comment by Spence1115** [comment]
@ChandanChainani if you look though, the state is coming through as `sleeping`. I have the same issue where the state in my `after` callback is the original state using (basically) the same code

```ruby
aasm do
    state :inactive, :initial => true
    state :active

    event :activate, after: :method_a do
      transitions from: :inactive, to: :active, after: :method_b
    end
  end

  def method_a
    puts "method a: job state should be `active`, job state is #{self.aasm_state}"
  end

  def method_b
    puts "method b: job state should be `active`, job state is #{self.aasm_state}"
  end
```
```
DEVELOPMENT [2] pry(main)> Subscription.last.activate!
[07:05] DEBUG   Subscription Load (0.5ms)  SELECT `subscriptions`.* FROM `subscriptions` ORDER BY `subscriptions`.`id` DESC LIMIT 1 
method b: job state should be `active`, job state is inactive
[07:05] DEBUG   TRANSACTION (1.3ms)  BEGIN 
[07:05] DEBUG   Subscription Update (0.3ms)  UPDATE `subscriptions` SET `subscriptions`.`updated_at` = '2022-09-13 06:05:25.196642', `subscriptions`.`aasm_state` = 'active' WHERE `subscriptions`.`id` = 1 
method a: job state should be `active`, job state is active
[07:05] DEBUG   TRANSACTION (0.6ms)  COMMIT 
```
In both methods, I would expect the state to be `active`, but it is not.

**Comment by MatthewRuddy** [comment]
@Spence1115 Did you find a solution this? I'm also experiencing the same behaviour.

**Comment by ChandanChainani** [comment]
The problem state by @MatthewRuddy and @Spence1115 seems correct.

@anilmaurya should I try to fix the same. Please suggest
